sudo: required

services:
  - docker

language: python

python:
  - '3.6'

before_install:
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xvzf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib/ && ./configure --prefix=/usr LDFLAGS="-lm" && make && sudo make install && cd .. && rm -r ta-lib
  
install:
  - pip install -e .[all-tests]

script: pytest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5d585e560cb2e7b4fe45
    on_success: change
    on_failure: always
    on_start: never